* Title Statistical Testing for AUC Data
* Version 1.0.0
* Maintainer Josh Gardner <jpgard@umich.edu>

#### Description 

Performs statistical testing to compare predictive models based on multiple observations of the A' statistic (also known as Area Under the Receiver Operating Characteristic Curve, or AUC). Specifically, it implements a testing method based on the equivalence between the A' statistic and the Wilcoxon statistic.

For more information, see Hanley and McNeil (1982) <doi:10.1148/radiology.143.1.7063747>.

* Imports dplyr, tidyr
* Depends R (>= 3.3.1)
* License MIT + file LICENSE
* Encoding UTF-8
* LazyData true
* RoxygenNote 6.0.1
* Suggests knitr, rmarkdown, testthat
* VignetteBuilder knitr
* NeedsCompilation no
* Author Josh Gardner [aut, cre]
Repository CRAN
Date/Publication 2017-11-13 09:46:18 UTC
R topics documented:
auctestr . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
auc_compare . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
fbh_test . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
sample_experiment_data . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5
se_auc . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
stouffer_z . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7


### auctestr auctestr: Statistical Testing for AUC data.

#### Description
auctestr currently provides four main useful functions for statistical testing of the AUC, or A’,
statistic: fbh_auc_compare, stouffer_z, fbh_test, and se_auc.

