---
title: "``add_scalebar``: Add scalebar to frames"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(timeVis)
```


centerItem Move the window such that given item or items are centered
### ### Description
Move the window such that given item or items are centered
### Usage
centerItem(id, itemId, options)
#### Arguments 
id Timeline id or a timevis object (the output from timevis())
itemId A vector (or single value) of the item ids to center
options Named list of options controlling mainly the animation. Most common option is
"animation" = TRUE/FALSE. For a full list of options, see the "focus" method
in the official Timeline documentation
Examples
timevis(data.frame(
id = 1:3,
start = c(Sys.Date() - 1, Sys.Date(), Sys.Date() + 1),
content = c("Item 1", "Item 2", "Item 3"))
) %>%
centerItem(1)
if (interactive()) {
library(shiny)
shinyApp(
ui = fluidPage(
timevisOutput("timeline"),
actionButton("btn", "Center around item 1")
),
server = function(input, output) {
output$timeline <- renderTimevis(
timevis(
data.frame(id = 1:3,
start = c(Sys.Date() - 1, Sys.Date(), Sys.Date() + 1),
content = c("Item 1", "Item 2", "Item 3"))
)
)
observeEvent(input$btn, {
centerItem("timeline", 1)
})
}
)
}
