

## distances: Tools for Distance Metrics

#### Description
The distances package provides tools for constructing, manipulating and using distance metrics
in R. It calculates distances only as needed (unlike the standard dist function which derives the
complete distance matrix when called). This saves memory and can increase speed. The package
also includes functions for fast nearest and farthest neighbor searching.

#### Details
See the package’s website for more information: https://github.com/fsavje/distances.
Bug reports and suggestions are greatly appreciated. They are best reported here: https://
github.com/fsavje/distances/issues/new.

Package ‘distances’
August 15, 2018
Type Package
Title Tools for Distance Metrics
* Version 0.1.4
* Date 2018-08-15
* Description Provides tools for constructing, manipulating and using distance metrics.
* Depends R (>= 3.4.0)
* Imports stats
* Suggests testthat
* NeedsCompilation yes
* License GPL (>= 3)
* LicenseNote The distances packages includes the ANN library  (distributed under the LGPLv2.1 license).
* URL https://github.com/fsavje/distances
* BugReports https://github.com/fsavje/distances/issues
* Encoding UTF-8
* RoxygenNote 6.0.1
* Author Fredrik Savje [aut, cre]
* Maintainer Fredrik Savje <fredrik.savje@yale.edu>
* Repository CRAN
* Date/Publication 2018-08-15 20:40:03 UTC

### Topics
R topics documented:

* distances-package
* distances 
* distance_columns
* distance_matrix 
* is.distances 
* max_distance_search 
* nearest_neighbor_search
