add_progress Add progress bar to frames
#### Description
This function adds a progress bar to animation frames created with frames_spatial.
Usage
add_progress(frames, colour = "grey", size = 1.8, verbose = TRUE)
#### Arguments 
frames list of ggplot2 objects, crated with frames_spatial.
colour character, progress bar colour.
size numeric, progress bar line size..
verbose logical, if TRUE, messages on the function’s progress are displayed (default).
Value
List of frames.
Author(s)
Jakob Schwalb-Willmann
See Also
frames_spatial frames_graph animate_frames
#### Examples
library(moveVis)
library(move)
data("move_data", "basemap_data")
m <- align_move(move_data, res = 4, unit = "mins")
# create spatial frames using a custom NDVI base layer
12 add_scalebar
r_list <- basemap_data[[1]]
r_times <- basemap_data[[2]]
frames <- frames_spatial(m, r_list = r_list, r_times = r_times, r_type = "gradient",
fade_raster = TRUE)
# add a progress bar:
frames.a <- add_progress(frames)
frames.a[[100]]
# or in red and larger
frames.b <- add_progress(frames, colour = "red", size = 2.5)
frames.b[[100]]
