Package ‘arsenal’
January 16, 2019
Title An Arsenal of 'R' Functions for Large-Scale Statistical
Summaries
Version 2.0.0
Date 2019-01-15

#### Description
 An Arsenal of 'R' functions for large-scale statistical summaries,
which are streamlined to work within the latest reporting tools in 'R' and
'RStudio' and which use formulas and versatile summary statistics for summary
tables and models. The primary functions include tableby(), a Table-1-like
summary of multiple variable types 'by' the levels of one or more categorical
variables; paired(), a Table-1-like summary of multiple variable types paired across
two time points; modelsum(), which performs simple model fits on one or more endpoints
for many variables (univariate or adjusted for covariates);
freqlist(), a powerful frequency table across many categorical variables;
compare.data.frame(), the S3 method for comparing data.frames; and
write2(), a function to output tables to a document.
Suggests broom, stringr, magrittr, knitr, rmarkdown, xtable, pander,
survival (>= 2.41-3), coin, pROC, MASS, gam, rpart, yaml
Depends R (>= 3.2.0), stats (>= 3.2.0)
Imports testthat, utils (>= 3.2.0)
URL https://github.com/eheinzen/arsenal,
https://cran.r-project.org/package=arsenal
BugReports https://github.com/eheinzen/arsenal/issues
VignetteBuilder knitr
License GPL (>= 2)
RoxygenNote 6.1.1
LazyData true
Encoding UTF-8
NeedsCompilation no
Author Ethan Heinzen [aut, cre],
Jason Sinnwell [aut],
1R topics documented:
2
Elizabeth Atkinson [aut],
Tina Gunderson [aut],
Gregory Dougherty [aut],
Patrick Votruba [ctb],
Ryan Lennon [ctb],
Andrew Hanson [ctb],
Krista Goergen [ctb],
Emily Lundt [ctb],
Brendan Broderick [ctb],
Maddie McCullough [art]
Maintainer Ethan Heinzen <heinzen.ethan@mayo.edu>
Repository CRAN
Date/Publication 2019-01-16 05:30:02 UTC
R topics documented:
arsenal . . . . . . . . . .
arsenal_table . . . . . .
as.data.frame.freqlist . .
as.data.frame.modelsum
as.data.frame.tableby . .
compare.data.frame . . .
comparison.control . . .
comparison.tolerances .
diffs . . . . . . . . . . .
formulize . . . . . . . .
freq.control . . . . . . .
freqlist . . . . . . . . . .
freqlist.internal . . . . .
internal.functions . . . .
keep.labels . . . . . . .
labels . . . . . . . . . .
mdy.Date . . . . . . . .
mockstudy . . . . . . . .
modelsum . . . . . . . .
modelsum.control . . . .
modelsum.family . . . .
modelsum.internal . . .
NA.operations . . . . . .
padjust . . . . . . . . . .
paired . . . . . . . . . .
paired.control . . . . . .
paired.internal . . . . . .
summary.compare . . . .
summary.freqlist . . . .
summary.modelsum . . .
summary.tableby . . . .

34arsenal
3
tableby . . . . . . . .
tableby.control . . .
tableby.internal . . .
tableby.stats . . . . .
tableby.stats.internal
write2 . . . . . . . .
write2.internal . . . .
write2specific . . . .
yaml . . . . . . . . .
%nin% . . . . . . . .
.
.
.
.
.
.
.
.
.
.
Index
arsenal.
36

52
An Arsenal of ’R’ Functions for Large-Scale Statistical Summaries

#### Description

An Arsenal of ’R’ functions for large-scale statistical summaries, which are streamlined to work
within the latest reporting tools in ’R’ and ’RStudio’ and which use formulas and versatile summary
statistics for summary tables and models.
Details
The package download, NEWS, and README are available on CRAN: https://cran.r-project.
org/package=arsenal
Functions
Below are listed some of the most widely used functions available in arsenal:
tableby: Summary statistics of a set of independent variables by a categorical variable.
paired: Summary statistics of a set of independent variables paired across two timepoints.
modelsum: Fit models over each of a set of independent variables with a response variable.
freqlist: Approximate the output from SAS’s PROC FREQ procedure when using the /list option
of the TABLE statement.
compare.data.frame: Compare two data.frames and report any differences between them, much
like SAS’s PROC COMPARE procedure.
write2word, write2html, write2pdf: Functions to output tables to a single Word, HTML, or PDF
document.
write2: Functions to output tables to a single document. (Also the S3 backbone behind the write2*
functions.)
keep.labels: Keep the 'label' attribute on an R object when subsetting.
formulize: A shortcut to generate one-, two-, or many-sided formulas.
mdy.Date and Date.mdy: Convert numeric dates for month, day, and year to Date object, and vice
versa.4
arsenal_table
is.Date: Test if an object is a date.
%nin%: Test for "not in".
allNA and includeNA: some useful functions for dealing with NAs.
Data
mockstudy: Mock study data for examples.

#### Examples

library(arsenal)
arsenal_table
arsenal tables with common structure

#### Description

arsenal tables with common structure

#### Usage
<pre><code>

has_strata(x)
## S3 method for class 'arsenal_table'
x[i, j, ...]
## S3 method for class 'arsenal_table'
labels(object, ...)
## S3 replacement method for class 'arsenal_table'
labels(x) <- value
## S3 method for class 'arsenal_table'
print(x, ...)
## S3 method for class 'arsenal_table'
merge(x, y, all = FALSE, all.x = all,
all.y = all, ...)
## S3 method for class 'freqlist'
merge(x, y, all = TRUE, ...)
## S3 method for class
print(x, ..., format =
(!is.null(x$text) &&
"markdown", escape =
min.split = NULL)
'summary.arsenal_table'
if
x$text %in% c("html", "latex")) x$text else
x$text %nin% c("html", "latex"), width = NULL,as.data.frame.freqlist
5

</code></pre>
#### Arguments

x, y, object An object of class "arsenal_table"
i, j A vector to index x with: either names of variables, a numeric vector, or a
logical vector of appropriate length. i indexes the x-variables, and j indexes the
by-variables.
... Other arguments (only used in print.summary.arsenal_table)
value
A list of new labels.
all, all.x, all.y
Logicals, denoting which terms to keep if not all are in common.
format
Passed to kable: the format for the table. The default here is "markdown".
To use the default in kable, pass NULL. If x$text specifies LaTeX or HTML
formatting, that format is used in the table.
escape
Passed to kable: should special characters be escaped when printed?
width, min.split
Passed to smart.split for formatting of the "term" column.
See Also
merge, labels
as.data.frame.freqlist
as.data.frame.freqlist

#### Description

Convert freqlist object to a data.frame.

#### Usage
<pre><code>

## S3 method for class 'freqlist'
as.data.frame(x, ..., labelTranslations = NULL,
list.ok = FALSE)

</code></pre>
#### Arguments

x
An object of class "freqlist".
...

</code></pre>
#### Arguments
 to pass to freq.control
labelTranslations
A named list (or vector) where the name is the label in the output to be replaced
in the pretty rendering by the character string value for the named element of
the list, e.g., list(age = "Age(Years)", meansd = "Mean(SD)").
list.ok
If the object has multiple by-variables, is it okay to return a list of data.frames
instead of a single data.frame? If FALSE but there are multiple by-variables, a
warning is issued.6
as.data.frame.modelsum

#### Value

A data.frame corresponding to the freqlist object.
as.data.frame.modelsum
as.data.frame.modelsum

#### Description

Coerce a modelsum object to a data.frame.

#### Usage
<pre><code>

## S3 method for class 'modelsum'
as.data.frame(x, ..., labelTranslations = NULL,
list.ok = FALSE)

</code></pre>
#### Arguments

x A modelsum object.
... 
</code></pre>
#### Arguments
 to pass to modelsum.control.
labelTranslations
A named list (or vector) where the name is the label in the output to be replaced
in the pretty rendering by the character string value for the named element of
the list, e.g., list(age = "Age(Years)", meansd = "Mean(SD)").
list.ok
If the object has multiple by-variables, is it okay to return a list of data.frames
instead of a single data.frame? If FALSE but there are multiple by-variables, a
warning is issued.

#### Value

A data.frame.
Author(s)
Ethan Heinzen, based on code originally by Greg Dougherty
See Also
modelsum, summary.modelsumas.data.frame.tableby
7
as.data.frame.tableby as.data.frame.tableby

#### Description

Coerce a tableby object to a data.frame.

#### Usage
<pre><code>

## S3 method for class 'tableby'
as.data.frame(x, ..., labelTranslations = NULL,
list.ok = FALSE)

</code></pre>
#### Arguments

* ``x``:  A tableby object.
... 
</code></pre>
#### Arguments
 to pass to tableby.control.
labelTranslations
A named list (or vector) where the name is the label in the output to be replaced
in the pretty rendering by the character string value for the named element of
the list, e.g., list(age = "Age(Years)", meansd = "Mean(SD)").
list.ok
If the object has multiple by-variables, is it okay to return a list of data.frames
instead of a single data.frame? If FALSE but there are multiple by-variables, a
warning is issued.

#### Value

A data.frame.
Author(s)
Ethan Heinzen, based on code originally by Greg Dougherty
See Also
tableby, tableby8
compare.data.frame
compare.data.frame
Compare two data.frames and report differences

#### Description

Compare two data.frames and report any differences between them, much like SAS’s PROC COMPARE
procedure.

#### Usage
<pre><code>

## S3 method for class 'data.frame'
compare(x, y, by = NULL, by.x = by, by.y = by,
control = NULL, ...)
## S3 method for class 'compare.data.frame'
print(x, ...)

</code></pre>
#### Arguments

x, y
A data.frame to compare
by, by.x, by.y Which variables are IDs to merge the two data.frames? If set to "row.names",
merging will occur over the row.names. If set to NULL (default), merging will
occur row-by-row.
control A list of control parameters from comparison.control.
... Other arguments, passed to comparison.control when appropriate.
Author(s)
Ethan Heinzen, adapted from code from Andrew Hanson
See Also
summary.compare.data.frame, n.diffs, n.diff.obs

#### Examples

df1 <- data.frame(id = paste0("person", 1:3), a = c("a", "b", "c"),
b = c(1, 3, 4), c = c("f", "e", "d"),
row.names = paste0("rn", 1:3), stringsAsFactors = FALSE)
df2 <- data.frame(id = paste0("person", 3:1), a = c("c", "b", "a"),
b = c(1, 3, 4), d = paste0("rn", 1:3),
row.names = paste0("rn", c(1,3,2)), stringsAsFactors = FALSE)
summary(compare(df1, df2))
summary(compare(df1, df2, by = "id"))
summary(compare(df1, df2, by = "row.names"))comparison.control
9
comparison.control
Control settings for ‘compare‘ function

#### Description

Control tolerance definitions for the compare.data.frame function.

#### Usage
<pre><code>

comparison.control(tol.logical = "none", tol.num = c("absolute",
"percent", "pct"), tol.num.val = sqrt(.Machine$double.eps),
int.as.num = FALSE, tol.char = c("none", "trim", "case", "both"),
tol.factor = c("none", "levels", "labels"), factor.as.char = FALSE,
tol.date = "absolute", tol.date.val = 0, tol.other = "none",
tol.vars = "none", ...)

</code></pre>
#### Arguments

tol.logical, tol.num, tol.char, tol.factor, tol.date, tol.other
A function or one of the shortcut character strings, denoting the tolerance func-
tion to use for a given data type. See "details", below.
tol.num.val Numeric; maximum value of differences allowed in numerics (fed to the func-
tion given in tol.num).
int.as.num Logical; should integers be coerced to numeric before comparison? Default
FALSE.
factor.as.char Logical; should factors be coerced to character before comparison? Default
FALSE.
tol.date.val Numeric; maximum value of differences allowed in dates (fed to the function
given in tol.date).
tol.vars Either "none" (the default), denoting that variable names are to be matched
as-is, or a character vector denoting equivalence classes for characters in the
variable names. See "details", below.
... Other arguments (not in use at this time).
Details
The following character strings are accepted:
• tol.logical = "none": compare logicals exactly as they are.
• tol.num = "absolute": compare absolute differences in numerics.
• tol.num = "percent", tol.num = "pct" compare percent differences in numerics.
• tol.char = "none": compare character strings exactly as they are.
• tol.char = "trim": left-justify and trim all trailing white space.
• tol.char = "case": allow differences in upper/lower case.10
comparison.tolerances
• tol.char = "both": combine "trim" and "case".
• tol.factor = "none": match both character labels and numeric levels.
• tol.factor = "levels": match only the numeric levels.
• tol.factor = "labels": match only the labels.
• tol.date = "absolute": compare absolute differences in dates.
• tol.other = "none": expect objects of other classes to be exactly identical.
tol.vars: If not set to "none" (the default), the tol.vars argument is a character vector denoting
equivalence classes for the characters in the variable names. A single character in this vector means
to replace that character with "". All other strings in this vector are split by character and replaced
by the first character in the string.
E.g., a character vector c("._", "aA", " ") would denote that the dot and underscore are equiv-
alent (to be translated to a dot), that "a" and "A" are equivalent (to be translated to "a"), and that
spaces should be removed.
The special character string "case" in this vector is the same as specifying paste0(letters, LETTERS).

#### Value

A list containing the necessary parameters for the compare.data.frame function.
Author(s)
Ethan Heinzen
See Also
compare.data.frame, comparison.tolerances

#### Examples

cntl <- comparison.control(
tol.num = "pct",
# calculate percent differences
tol.vars = c("case", # ignore case
"._",
# set all underscores to dots.
"e")
# remove all letter e's
)
comparison.tolerances Comparison tolerances

#### Description

Internal functions defining tolerances for the comparison.control function. To create your own
tolerance definitions, see the vignette.comparison.tolerances
11

#### Usage
<pre><code>

tol.NA(x, y, idx)
tol.num.absolute(x, y, tol)
tol.num.percent(x, y, tol)
tol.num.pct(x, y, tol)
tol.factor.none(x, y)
tol.factor.levels(x, y)
tol.factor.labels(x, y)
tol.char.both(x, y)
tol.char.case(x, y)
tol.char.trim(x, y)
tol.char.none(x, y)
tol.date.absolute(x, y, tol)
tol.logical.none(x, y)
tol.other.none(x, y)

</code></pre>
#### Arguments

x, y
idx
tol
vectors of the appropriate lengths and types.
A logical vector of appropriate length.
A numeric tolerance
Details
tol.NA takes as differences between two vectors any elements which are NA in one but not the
other, or which are non-NA in both and TRUE in idx. It is useful for handling NAs in custom
tolerance functions.

#### Value

A logical vector of length equal to that of x and y, where TRUE denotes a difference between x and
y, and FALSE denotes no difference between x and y.
Author(s)
Ethan Heinzen12
diffs
See Also
comparison.control, compare.data.frame
diffs
Extract differences

#### Description

Extract differences, number of differences, or number of not-shared observations from a compare
object.

#### Usage
<pre><code>

n.diff.obs(object, ...)
## S3 method for class 'compare.data.frame'
n.diff.obs(object, ...)
## S3 method for class 'summary.compare.data.frame'
n.diff.obs(object, ...)
n.diffs(object, ...)
## S3 method for class 'compare.data.frame'
n.diffs(object, ...)
## S3 method for class 'summary.compare.data.frame'
n.diffs(object, ...)
diffs(object, ...)
## S3 method for class 'compare.data.frame'
diffs(object, vars = NULL, ...,
by.var = FALSE)
## S3 method for class 'summary.compare.data.frame'
diffs(object, vars = NULL, ...,
by.var = FALSE)

</code></pre>
#### Arguments

object An object of class compare.data.frame or summary.compare.data.frame.
... Other arguments (not in use at this time).
vars A character vector of variable names to subset the results to.
by.var Logical: should the number of differences by variable be reported, or should all
differences be reported (the default).formulize
13
Author(s)
Ethan Heinzen
See Also
compare.data.frame summary.compare.data.frame
formulize
formulize

#### Description

A shortcut to generate one-, two-, or many-sided formulas from vectors of variable names.

#### Usage
<pre><code>

formulize(y = "", x = "", ..., data = NULL)

</code></pre>
#### Arguments

y, x, ... Character vectors, names, or calls to be collapsed (by "+") and put left-to-right
in the formula. If data is supplied, these can also be numeric, denoting which
column name to use. See examples.
data An R object with non-null column names.
Author(s)
Ethan Heinzen
See Also
reformulate

#### Examples

## two-sided formula
formulize("y", c("x1", "x2", "x3"))
## one-sided formula
formulize(x = c("x1", "x2", "x3"))
## multi-sided formula
formulize("y", c("x1", "x2", "x3"), c("z1", "z2"), "w1")
## can use numerics for column names
data(mockstudy)
formulize(y = 1, x = 2:4, data = mockstudy)14
freq.control
## mix and match
formulize(1, c("x1", "x2", "x3"), data = mockstudy)
## get an interaction
formulize("y", c("x1*x2", "x3"))
## no intercept
formulize("y", "x1 - 1")
formulize("y", c("x1", "x2", "-1"))
## use in an lm
form <- formulize(2, 3:4, data = mockstudy)
summary(lm(form, data = mockstudy))
## using non-syntactic names or calls (like reformulate example)
formulize(as.name("+-"), c("`P/E`", "`% Growth`"))
f <- Surv(ft, case) ~ a + b
formulize(f[[2]], f[[3]])
freq.control
Control settings for freqlist function

#### Description

Control test and summary settings for the freqlist function.

#### Usage
<pre><code>

freq.control(sparse = FALSE, single = FALSE, dupLabels = FALSE,
digits.count = 0L, digits.pct = 2L, ..., digits = NULL)

</code></pre>
#### Arguments

sparse a logical value indicating whether to keep rows with counts of zero. The default
is FALSE (drop zero-count rows).
single logical, indicating whether to collapse results created using a strata variable into
a single table for printing
dupLabels logical: should labels which are the same as the row above be printed? The
default (FALSE) more closely approximates PROC FREQ output from SAS, where
a label carried down from the row above is left blank.
digits.count Number of decimal places for count values.
digits.pct Number of decimal places for percents.
* ``... ``: additional arguments.
digits A deprecated argumentfreqlist
15

#### Value

A list with settings to be used within the freqlist function.
Author(s)
Ethan Heinzen
See Also
freqlist, summary.freqlist
freqlist
freqlist

#### Description

Approximate the output from SAS’s PROC FREQ procedure when using the /list option of the
TABLE statement.

#### Usage
<pre><code>

freqlist(object, ...)
## S3 method for class 'table'
freqlist(object, na.options = c("include", "showexclude",
"remove"), strata = NULL, labelTranslations = NULL, control = NULL,...)
## S3 method for class 'formula'
freqlist(formula, data, subset, na.action,
strata = NULL, labelTranslations = NULL, control = NULL, addNA,
exclude, drop.unused.levels, ...)

</code></pre>
#### Arguments

* ``object``:  An R object, usually of class "table" or class "xtabs"
* ``... ``: additional arguments. In the formula method, these are passed to the table
method. These are also passed to freq.control
na.options a character string indicating how to handling missing values: "include" (in-
clude values with NAs in counts and percentages), "showexclude" (show NAs
but exclude from cumulative counts and all percentages), "remove" (remove
values with NAs); default is "include".
strata (formerly groupBy) an optional character string specifying a variable(s) to use
for grouping when calculating cumulative counts and percentages. summary.freqlist
will also separate by grouping variable for printing. Note that this is different
from modelsum and tableby, which take bare column names (and only one, at
that!)16
freqlist.internal
labelTranslations
an optional character string (or list) of labels to use for variable levels when
summarizing. Names will be matched appropriately.
control
control parameters to handle optional settings within freqlist. See freq.control
formula, data, subset, na.action, addNA, exclude, drop.unused.levels

Arguments passed to xtabs. Note that addNA= only works in R >= 3.4.0.

#### Value

An object of class c("freqlist", "arsenal_table")
Author(s)
Tina Gunderson, with revisions by Ethan Heinzen
See Also
arsenal_table, summary.freqlist, freq.control, table, xtabs, kable

#### Examples
```{r}
# load mockstudy data
data(mockstudy)
tab.ex <- table(mockstudy[c("arm", "sex", "mdquality.s")], useNA = "ifany")
noby <- freqlist(tab.ex, na.options = "include")
summary(noby)
withby <- freqlist(tab.ex, strata = c("arm","sex"), na.options = "showexclude")
summary(withby)
```


freqlist.internal
Helper functions for freqlist

#### Description

A set of helper functions for freqlist.

#### Usage
<pre><code>

is.freqlist(x)
is.summary.freqlist(x)

</code></pre>
#### Arguments

x
A freqlist object.
See Also
merge.freqlist, arsenal_table

## ``internal.functions``
Split a string into pieces intelligently

#### Description

Split a string into pieces intelligently

#### Usage
<pre><code>

smart.split(string, width = Inf, min.split = -Inf)
replace2(x, list, values)

</code></pre>
#### Arguments

* ``string``:  A character vector 
width Either Inf or NULL to specify no splitting, or a positive integer giving the largest
allowed string length.
* ``min.split``:   Either -Inf or NULL to specify no lower bound on the string length, or a positive integer giving the minimum string length.
x vector
list an index vector
* ``values``: replacement values

#### Value

For smart.split, a list of the same length as string, with each element being the "intelligently"
split string.
For replace2, a vector with the proper values replaced.
See Also
replace
keep.labels
Keep Labels

#### Description

Keep the 'label' attribute on an R object when subsetting.18
labels

#### Usage
<pre><code>

keep.labels(x, ...)
## S3 method for class 'data.frame'
keep.labels(x, ...)
## Default S3 method:
keep.labels(x, ...)
## S3 method for class 'keep_labels'
x[...]

</code></pre>
#### Arguments

x An R object
... Other arguments (not in use at this time).

#### Value

A copy of x with a "keep labels" class appended on.
Author(s)
Ethan Heinzen
See Also
labels
labels
Labels

#### Description

Assign and extract the 'label' attribute on an R object. set_labels is the same as labels(x) <- value
but returns x for use in a pipe chain. set_attr is the same as attr(x, which) <- value but re-
turns x for use in a pipe chain.

#### Usage
<pre><code>

## S3 method for class 'data.frame'
labels(object, ...)
## S3 method for class 'keep_labels'
labels(object, ...)
labels(x) <- valuemdy.Date
19
## S3 replacement method for class 'keep_labels'
labels(x) <- value
## Default S3 replacement method:
labels(x) <- value
## S3 replacement method for class 'data.frame'
labels(x) <- value
set_labels(x, value)
set_attr(x, which, value)

</code></pre>
#### Arguments

... Other arguments (not in use at this time).
x, * ``object``:  An R object.
* ``value``: A vector or list containing labels to assign. Labels are assigned based on names,
if available; otherwise, they’re assigned in order. Can pass NULL to remove all
labels.
which See attr<-
Details
The data.frame methods put labels on and extract labels from the columns of object.

#### Value

The labels of object, or object with new labels.
Author(s)
Ethan Heinzen
See Also
keep.labels




mockstudy
mockstudy
21
Mock study data for examples

#### Description

Mock clinical study data for examples to test data manipulation and statistical functions. The func-
tion muck_up_mockstudy() is used in examples for compare.data.frame.

#### Usage
<pre><code>

mockstudy
muck_up_mockstudy()
Format
A data frame with 1499 observations on the following 15 variables:
case a numeric identifier-patient ID
age age in years
arm treatment arm divided into 3 groups, character string
sex a factor with levels Male Female
race self-reported race/ethnicity, character string
fu.time survival or censoring time in years
fu.stat censoring status; 1=censor, 2=death
ps integer, ECOG performance score
hgb numeric, hemoglobin count
bmi numeric, body mass index, kg/m^2
alk.phos numeric, alkaline phosphatase
ast numeric, aspartate transaminase
mdquality.s integer, LASA QOL 0=Clinically Deficient, 1=Not Clinically Deficient
age.ord an ordered factor split of age, with levels 10-19 < 20-29 < 30-39 < 40-49 < 50-59 <
60-69 < 70-79 < 80-89

#### Examples

data(mockstudy)
str(mockstudy)




modelsum.control
Control settings for modelsum function

#### Description

Control test and summary settings for modelsum function.

#### Usage
<pre><code>

modelsum.control(digits = 3L, digits.ratio = 3L, digits.p = 3L,
format.p = TRUE, show.adjust = TRUE, show.intercept = TRUE,
conf.level = 0.95, ordinal.stats = c("OR", "CI.lower.OR",
"CI.upper.OR", "p.value", "Nmiss"), binomial.stats = c("OR",
"CI.lower.OR", "CI.upper.OR", "p.value", "concordance", "Nmiss"),
gaussian.stats = c("estimate", "std.error", "p.value", "adj.r.squared",
"Nmiss"), poisson.stats = c("RR", "CI.lower.RR", "CI.upper.RR",
"p.value", "Nmiss"), negbin.stats = c("RR", "CI.lower.RR",
"CI.upper.RR", "p.value", "Nmiss"), survival.stats = c("HR",
"CI.lower.HR", "CI.upper.HR", "p.value", "concordance", "Nmiss"),
stat.labels = list(), ...)24
modelsum.family

</code></pre>
#### Arguments

digits Numeric, denoting the number of digits after the decimal point for beta coeffi-
cients and standard errors.
digits.ratio Numeric, denoting the number of digits after the decimal point for ratios, e.g.
OR, RR, HR.
digits.p Numeric, denoting the number of digits for p-values. See "Details", below.
format.p Logical, denoting whether to format p-values. See "Details", below.
show.adjust Logical, denoting whether to show adjustment terms.
show.intercept Logical, denoting whether to show intercept terms.
conf.level
Numeric, giving the confidence level.
ordinal.stats, binomial.stats, survival.stats, gaussian.stats, poisson.stats, negbin.stats
Character vectors denoting which stats to show for the various model types.
stat.labels A named list of labels for all the stats used above.
... Other arguments (not in use at this time).
Details
If format.p is FALSE, digits.p denotes the number of significant digits shown. The p-values will
be in exponential notation if necessary. If format.p is TRUE, digits.p will determine the number
of digits after the decimal point to show. If the p-value is less than the resulting number of places,
it will be formatted to show so.

#### Value

A list with settings to be used within the modelsum function.
See Also
modelsum, summary.modelsum
modelsum.family
Family functions for modelsum

#### Description

A set of family functions for modelsum.

#### Usage
<pre><code>

survival()
ordinal(method = c("logistic", "probit", "loglog", "cloglog", "cauchit"))
negbin(link = c("log", "identity", "sqrt"))modelsum.internal
25

</code></pre>
#### Arguments

method See MASS::polr.
link See MASS::glm.nb.

#### Value

A list, in particular with element family.
See Also
family, coxph, polr
modelsum.internal
Helper functions for modelsum

#### Description

A set of helper functions for modelsum.

#### Usage
<pre><code>

is.modelsum(x)
is.summary.modelsum(x)
na.modelsum(object, ...)

</code></pre>
#### Arguments

x A modelsum object.
object A data.frame resulting from evaluating a modelsum formula.
... Other arguments, or a vector of indices for extracting.

#### Value

na.modelsum returns a subsetted version of object (with attributes).
See Also
arsenal_table26
padjust
NA.operations
Some functions to handle NAs

#### Description

allNA tests if all elements are NA, and includeNA sets the NAs in a character vector or factor to an
explicit label.

#### Usage
<pre><code>

allNA(x)
includeNA(x, label, ...)
## S3 method for class 'factor'
includeNA(x, label = "(Missing)", first = FALSE, ...)
## Default S3 method:
includeNA(x, label = "(Missing)", ...)

</code></pre>
#### Arguments

x An object
label A character string denoting the label to set NAs to.
... Other arguments (not in use at this time).
first Logical; should the new label be the first level?
Author(s)
Ethan Heinzen
See Also
is.na, anyNA
padjust
Adjust P-values for Multiple Comparisons

#### Description

Adjust P-values for Multiple Comparisonspaired
27

#### Usage
<pre><code>

padjust(p, method, n, ...)
## Default S3 method:
padjust(p, method, n, ...)
## S3 method for class 'tableby'
padjust(p, method, n,
suffix = " (adjusted for multiple comparisons)", ...)
## S3 method for class 'summary.tableby'
padjust(p, method, n,
suffix = " (adjusted for multiple comparisons)", ...)

</code></pre>
#### Arguments

p An object.
method correction method. Can be abbreviated.
n number of comparisons, must be at least length(p); only set this (to non-
default) when you know what you are doing!
... Other arguments.
suffix A suffix to add to the footnotes indicating that the tests were adjusted.
See Also
p.adjust, modpval.tableby, tests.tableby


paired.control
29
Control settings for paired function

#### Description

Control test and summary settings for the paired function.

#### Usage
<pre><code>

paired.control(test = TRUE, diff = TRUE, test.pname = NULL,
numeric.test = "paired.t", cat.test = "mcnemar",
ordered.test = "signed.rank", date.test = "paired.t",
numeric.stats = c("Nmiss", "meansd", "range"), cat.stats = c("Nmiss",
"countpct"), ordered.stats = c("Nmiss", "countpct"),
date.stats = c("Nmiss", "median", "range"), stats.labels = list(Nmiss
= "N-Miss", Nmiss2 = "N-Miss", meansd = "Mean (SD)", medianq1q3 =
"Median (Q1, Q3)", q1q3 = "Q1, Q3", range = "Range", countpct =
"Count (Pct)"), digits = 3L, digits.count = 0L, digits.p = 3L,
format.p = TRUE, conf.level = 0.95, mcnemar.correct = TRUE,
signed.rank.exact = NULL, signed.rank.correct = TRUE, ...)

</code></pre>
#### Arguments

test logical, telling paired whether to perform tests of x variables across time points.
diff logical, telling paired whether to calculate a column of differences between
time points.
* ``test.pname``:  character string denoting the p-value column name in summary.tableby. Mod-
ifiable also with modpval.tableby.
* ``numeric.test``:  name of test for numeric RHS variables in paired: paired.t, signed.rank, sign.test.
cat.test name of test for categorical variables: mcnemar
* ``ordered.test ``:  name of test for ordered variables: signed.rank, sign.test
date.test name of test to perform for date variables: paired.t, signed.rank, sign.test
numeric.stats summary statistics to include for numeric RHS variables within the levels of the
group LHS variable. Options are N, Nmiss, Nmiss2, mean, meansd, median,
q1q3, medianq1q3, iqr, range, medianrange, or other R built-in or user-written
functions.
* ``cat.stats ``:   summary statistics to include for categorical RHS variables within the levels
of the group LHS variable. Options are N, Nmiss, Nmiss2, count, countpct,
countrowpct, countcellpct, or other R built-in or user-written functions.
ordered.stats summary statistics to include for categorical RHS variables within the levels
of the group LHS variable. Options are N, Nmiss, count, countpct, or other R
built-in or user-written functions.
date.stats stats functions to perform for Date variables: Nmiss, median, range, median-
range, q1q3, medianq1q3, or other R built-in or user-written functions.30
paired.internal
stats.labels A named list of labels for all the statistics function names, where the function
name is the named element in the list and the value that goes with it is a string
containing the formal name that will be printed in all printed renderings of the
output, e.g., list(countpct="Count (Pct)").
digits Number of decimal places for numeric values.
digits.count Number of decimal places for count values.
digits.p Number of decimal places for p-values.
format.p Logical, denoting whether to format p-values. See "Details", below.
conf.level
Numeric, denoting what confidence level to use for confidence intervals. (See,
e.g., binomCI)
mcnemar.correct, signed.rank.exact, signed.rank.correct
Options for statistical tests. See wilcox.test and mcnemar.test for details.
...
additional arguments.
Details
All tests can be turned off by setting test to FALSE. Otherwise, test are set to default settings in
this list, or set explicitly in the formula of tableby.
If format.p is FALSE, digits.p denotes the number of significant digits shown. The p-values will
be in exponential notation if necessary. If format.p is TRUE, digits.p will determine the number
of digits after the decimal point to show. If the p-value is less than the resulting number of places,
it will be formatted to show so.

#### Value

A list with settings to be used within the paired function.
Author(s)
Ethan Heinzen
See Also
paired, tableby, tableby.control, summary.tableby
paired.internal
Helper functions for paired

#### Description

A set of helper functions for paired.

#### Usage
<pre><code>

na.paired(missings = c("in.both", "fill", "asis"))summary.compare
31

</code></pre>
#### Arguments

missings A character string denoting which action to take. See "Details", below.
... Other arguments, or a vector of indices for extracting.
Details
All methods subset out any NA time points or IDs. "in.both" (the default) subsets the data.frame
to individuals who appear at both time points. "fill" adds explicit missings for the people missing
second time points. "asis" does nothing to add or remove missings.

#### Value

na.paired returns a function used to subset data.frames in paired.
See Also
tableby.internal





Internal tableby functions

#### Description

A collection of functions that may help users create custom functions that are formatted correctly.

#### Usage
<pre><code>

as.tbstat(x, oldClass = NULL, sep = NULL, parens = NULL,
sep2 = NULL, pct = NULL)
as.countpct(x, ...)
as.tbstat_multirow(x)

</code></pre>
#### Arguments

x Usually a vector.
oldClass class(es) to add to the resulting object.
sep The separator between x[1] and the rest of the vector.
parens A length-2 vector denoting parentheses to use around x[2] and x[3].
sep2 The separator between x[2] and x[3].
pct The symbol to use after percents.
... arguments to pass to as.tbstat.write2
45
Details
as.tbstat defines a tableby statistic with its appropriate formatting.
as.countpct adds another class to as.tbstat to use different "digits" arguments. See tableby.control.
as.tbstat_multirow marks an object (usually a list) for multiple-row printing.
write2
write2

#### Description

Functions to output tables to a single document. (Also the S3 backbone behind the write2* func-
tions.)

#### Usage
<pre><code>

write2(object, file, ..., output_format)
## S3 method for class 'arsenal_table'
write2(object, file, ..., output_format = NULL)
## S3 method for class 'summary.arsenal_table'
write2(object, file, ...,
output_format = NULL)
## S3 method for class 'compare.data.frame'
write2(object, file, ...,
output_format = NULL)
## S3 method for class 'summary.compare.data.frame'
write2(object, file, ...,
output_format = NULL)
## S3 method for class 'verbatim'
write2(object, file, ..., output_format = NULL)
## S3 method for class 'yaml'
write2(object, file, ..., output_format = NULL)
## S3 method for class 'code.chunk'
write2(object, file, ..., output_format = NULL)
## S3 method for class 'knitr_kable'
write2(object, file, ..., output_format = NULL)
## S3 method for class 'xtable'
write2(object, file, ..., output_format = NULL)46
write2
## S3 method for class 'character'
write2(object, file, ..., output_format = NULL)
## S3 method for class 'list'
write2(object, file, ..., append. = FALSE,
render. = TRUE, keep.rmd = !render., output_format = NULL)
## Default S3 method:
write2(object, file, FUN = NULL, ...,
append. = FALSE, render. = TRUE, keep.rmd = !render.,
output_format = NULL)

</code></pre>
#### Arguments

object An object.
file A single character string denoting the filename for the output document.
... Additional arguments to be passed to FUN, rmarkdown::render, etc. One pop-
ular option is to use quiet = TRUE to suppress the command line output.
output_format One of the following:
1. An output format object, e.g. rmarkdown::html_document(...).
2. A character string denoting such a format function, e.g. "html_document".
In this case, the "..." are NOT passed.
3. The format function itself, e.g. rmarkdown::html_document. In this case,
the "..." arguments are passed.
4. One of "html", "pdf", and "word", shortcuts implemented here. In this
case, the "..." arguments are passed.
5. NULL, in which the output is HTML by default.
See rmarkdown::render for details.
append. Logical, denoting whether (if a temporary .Rmd file of the same name already
exists) to append on. Used mostly for write2.list.
render. Logical, denoting whether to render the temporary .Rmd file. Used mostly for
write2.list.
keep.rmd Logical, denoting whether to keep the intermediate .Rmd file. Used mostly for
write2.list.
FUN The summary-like or print-like function to use to generate the markdown con-
tent. Can be passed as a function or a character string. It’s expected that
FUN(object, ...) looks "good" when put directly in a .Rmd file.
Details
write2 is an S3 method. The default prints the object (using print) inside a section surrounded by
three back ticks. See verbatim for details.
There are methods implemented for tableby, modelsum, and freqlist, all of which use the
summary function. There are also methods compatible with kable, xtable, and pander_return.write2.internal
47
Another option is to coerce an object using verbatim() to print out the results monospaced (as if
they were in the terminal). To output multiple tables into a document, simply make a list of them and
call the same function as before. Finally, to output code chunks to be evaluated, use code.chunk.
For more information, see vignette("write2").

#### Value

object is returned invisibly, and file is written.
Author(s)
Ethan Heinzen, adapted from code from Krista Goergen
See Also
write2word, write2pdf, write2html, render, word_document, html_document, pdf_document,
rtf_document, md_document, odt_document

#### Examples

## Not run:
data(mockstudy)
# tableby example
tab1 <- tableby(arm ~ sex + age, data=mockstudy)
write2(tab1, tempfile(fileext = ".rtf"),
toc = TRUE, # passed to rmarkdown::rtf_document, though in this case it's not practical
quiet = TRUE, # passed to rmarkdown::render
title = "My cool new title", # passed to summary.tableby
output_format = rmarkdown::rtf_document)
## End(Not run)
write2html(list(
"# Header 1", # a header
code.chunk(a <- 1, b <- 2, a + b), # a code chunk
verbatim("hi there") # verbatim output
),
tempfile(fileext = ".html"),
quite = TRUE)
write2.internal
Helper functions for write2

#### Description

Helper functions for write2.48
write2specific

#### Usage
<pre><code>

## S3 method for class 'verbatim'
print(x, ...)
verbatim(x)
code.chunk(..., chunk.opts = "r")
## S3 method for class 'code.chunk'
print(x, ...)

</code></pre>
#### Arguments

x An R object to coerce to class "verbatim" or such an object to print.
... For print.verbatim, other arguments passed to print. For code.chunk, either
expressions or single character strings to paste into the code chunk. Not used
for print.code.chunk.
chunk.opts A single character string giving the code chunk options. Make sure to specify
the engine!
Details
The "verbatim" class is to tell write2 to print the object inside a section surrounded by three back
ticks. The results will look like it would in the terminal (monospaced).
code.chunk() is to write explicit code chunks in the .Rmd file; it captures the call and writes it to
the file, to execute upon knitting.
write2specific
write2word, write2html, write2pdf

#### Description

Functions to output tables to a single Word, HTML, or PDF document.

#### Usage
<pre><code>

write2word(object, file, ...)
write2pdf(object, file, ...)
write2html(object, file, ...)write2specific
49

</code></pre>
#### Arguments

object An object.
file A single character string denoting the filename for the output document.
... Additional arguments to be passed to FUN, rmarkdown::render, etc. One pop-
ular option is to use quiet = TRUE to suppress the command line output.
Details
To generate the appropriate file type, the write2* functions use one of rmarkdown::word_document,
rmarkdown::html_document, and rmarkdown::pdf_document to get the job done. "..." argu-
ments are passed to these functions, too.

#### Value

object is returned invisibly, and file is written.
Author(s)
Ethan Heinzen, adapted from code from Krista Goergen
See Also
write2

#### Examples

## Not run:
data(mockstudy)
# tableby example
tab1 <- tableby(arm ~ sex + age, data=mockstudy)
write2html(tab1, "~/trash.html")
# freqlist example
tab.ex <- table(mockstudy[, c("arm", "sex", "mdquality.s")], useNA = "ifany")
noby <- freqlist(tab.ex, na.options = "include")
write2pdf(noby, "~/trash2.pdf")
# A more complicated example
write2word(tab1, "~/trash.doc",
keep.md = TRUE,
reference_docx = mystyles.docx, # passed to rmarkdown::word_document
quiet = TRUE, # passed to rmarkdown::render
title = "My cool new title") # passed to summary.tableby
## End(Not run)


yaml
Include a YAML header in write2

#### Description

Include a YAML header in write2

#### Usage
<pre><code>

yaml(...)
## S3 method for class 'yaml'
print(x, ...)
## S3 method for class 'yaml'
c(..., recursive = FALSE)
is.yaml(x)

</code></pre>
#### Arguments

... For yaml(), arguments to be bundled into a list and passed to as.yaml. For
print.yaml(), extra arguments. For c.yaml(), "yaml" objects to be concate-
nated.
* ``x``: An object of class "yaml".
recursive Not in use at this time.

#### Value

A text string of class "yaml".
Author(s)
Ethan Heinzen, adapted from an idea by Brendan Broderick
See Also
as.yaml, write2

#### Examples

x <- yaml(title = "My cool title", author = "Ethan P Heinzen")
x
y <- yaml("header-includes" = list("\\usepackage[labelformat=empty]{caption}"))
y
c(x, y)%nin%
51
%nin%
Not in

#### Description

The not-in operator for R.

#### Usage
<pre><code>

x %nin% table

</code></pre>
#### Arguments

x vector or NULL: the values to be matched. Long vectors are supported.
table vector or NULL: the values to be matched against. Long vectors are not supported.

#### Value

The negation of %nin%.
Author(s)
Raymond Moore
See Also
%in%

#### Examples

1 %nin% 2:10
c("a", "b") %nin% c("a", "c", "d")
