Package ‘arsenal’
January 16, 2019
Title An Arsenal of 'R' Functions for Large-Scale Statistical
Summaries
Version 2.0.0
Date 2019-01-15

#### Description
 An Arsenal of 'R' functions for large-scale statistical summaries,
which are streamlined to work within the latest reporting tools in 'R' and
'RStudio' and which use formulas and versatile summary statistics for summary
tables and models. The primary functions include tableby(), a Table-1-like
summary of multiple variable types 'by' the levels of one or more categorical
variables; paired(), a Table-1-like summary of multiple variable types paired across
two time points; modelsum(), which performs simple model fits on one or more endpoints
for many variables (univariate or adjusted for covariates);
freqlist(), a powerful frequency table across many categorical variables;
compare.data.frame(), the S3 method for comparing data.frames; and
write2(), a function to output tables to a document.
Suggests broom, stringr, magrittr, knitr, rmarkdown, xtable, pander,
survival (>= 2.41-3), coin, pROC, MASS, gam, rpart, yaml
Depends R (>= 3.2.0), stats (>= 3.2.0)
Imports testthat, utils (>= 3.2.0)
URL https://github.com/eheinzen/arsenal,
https://cran.r-project.org/package=arsenal
BugReports https://github.com/eheinzen/arsenal/issues
VignetteBuilder knitr
License GPL (>= 2)
RoxygenNote 6.1.1
LazyData true
Encoding UTF-8
NeedsCompilation no
Author Ethan Heinzen [aut, cre],
Jason Sinnwell [aut],
1R topics documented:
2
Elizabeth Atkinson [aut],
Tina Gunderson [aut],
Gregory Dougherty [aut],
Patrick Votruba [ctb],
Ryan Lennon [ctb],
Andrew Hanson [ctb],
Krista Goergen [ctb],
Emily Lundt [ctb],
Brendan Broderick [ctb],
Maddie McCullough [art]
Maintainer Ethan Heinzen <heinzen.ethan@mayo.edu>
Repository CRAN
Date/Publication 2019-01-16 05:30:02 UTC
R topics documented:
arsenal . . . . . . . . . .
arsenal_table . . . . . .
as.data.frame.freqlist . .
as.data.frame.modelsum
as.data.frame.tableby . .
compare.data.frame . . .
comparison.control . . .
comparison.tolerances .
diffs . . . . . . . . . . .
formulize . . . . . . . .
freq.control . . . . . . .
freqlist . . . . . . . . . .
freqlist.internal . . . . .
internal.functions . . . .
keep.labels . . . . . . .
labels . . . . . . . . . .
mdy.Date . . . . . . . .
mockstudy . . . . . . . .
modelsum . . . . . . . .
modelsum.control . . . .
modelsum.family . . . .
modelsum.internal . . .
NA.operations . . . . . .
padjust . . . . . . . . . .
paired . . . . . . . . . .
paired.control . . . . . .
paired.internal . . . . . .
summary.compare . . . .
summary.freqlist . . . .
summary.modelsum . . .
summary.tableby . . . .

34arsenal
3
tableby . . . . . . . .
tableby.control . . .
tableby.internal . . .
tableby.stats . . . . .
tableby.stats.internal
write2 . . . . . . . .
write2.internal . . . .
write2specific . . . .
yaml . . . . . . . . .
%nin% . . . . . . . .
.
.
.
.
.
.
.
.
.
.
Index
arsenal.
36

52
An Arsenal of ’R’ Functions for Large-Scale Statistical Summaries

#### Description

An Arsenal of ’R’ functions for large-scale statistical summaries, which are streamlined to work
within the latest reporting tools in ’R’ and ’RStudio’ and which use formulas and versatile summary
statistics for summary tables and models.
Details
The package download, NEWS, and README are available on CRAN: https://cran.r-project.
org/package=arsenal
Functions
Below are listed some of the most widely used functions available in arsenal:
tableby: Summary statistics of a set of independent variables by a categorical variable.
paired: Summary statistics of a set of independent variables paired across two timepoints.
modelsum: Fit models over each of a set of independent variables with a response variable.
freqlist: Approximate the output from SAS’s PROC FREQ procedure when using the /list option
of the TABLE statement.
compare.data.frame: Compare two data.frames and report any differences between them, much
like SAS’s PROC COMPARE procedure.
write2word, write2html, write2pdf: Functions to output tables to a single Word, HTML, or PDF
document.
write2: Functions to output tables to a single document. (Also the S3 backbone behind the write2*
functions.)
keep.labels: Keep the 'label' attribute on an R object when subsetting.
formulize: A shortcut to generate one-, two-, or many-sided formulas.
mdy.Date and Date.mdy: Convert numeric dates for month, day, and year to Date object, and vice
versa.4
arsenal_table
is.Date: Test if an object is a date.
%nin%: Test for "not in".
allNA and includeNA: some useful functions for dealing with NAs.
Data
mockstudy: Mock study data for examples.

#### Examples

library(arsenal)
