
---
title: "``arsenal::paired.control``"
2output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(arsenal)
```



Control settings for paired function

#### Description

Control test and summary settings for the paired function.

#### Usage
<pre><code>

paired.control(test = TRUE, diff = TRUE, test.pname = NULL,
numeric.test = "paired.t", cat.test = "mcnemar",
ordered.test = "signed.rank", date.test = "paired.t",
numeric.stats = c("Nmiss", "meansd", "range"), cat.stats = c("Nmiss",
"countpct"), ordered.stats = c("Nmiss", "countpct"),
date.stats = c("Nmiss", "median", "range"), stats.labels = list(Nmiss
= "N-Miss", Nmiss2 = "N-Miss", meansd = "Mean (SD)", medianq1q3 =
"Median (Q1, Q3)", q1q3 = "Q1, Q3", range = "Range", countpct =
"Count (Pct)"), digits = 3L, digits.count = 0L, digits.p = 3L,
format.p = TRUE, conf.level = 0.95, mcnemar.correct = TRUE,
signed.rank.exact = NULL, signed.rank.correct = TRUE, ...)

</code></pre>
#### Arguments

* ``test``: logical, telling paired whether to perform tests of x variables across time points.
* ``diff``: logical, telling paired whether to calculate a column of differences between time points.
* ``test.pname``:  character string denoting the p-value column name in summary.tableby. Modifiable also with modpval.tableby.
* ``numeric.test``:  name of test for numeric RHS variables in paired: paired.t, signed.rank, sign.test.
* ``cat.test``: name of test for categorical variables: mcnemar
* ``ordered.test ``:  name of test for ordered variables: signed.rank, sign.test
* ``date.test``: name of test to perform for date variables: paired.t, signed.rank, sign.test
* ``numeric.stats``: summary statistics to include for numeric RHS variables within the levels of the group LHS variable. Options are N, Nmiss, Nmiss2, mean, meansd, median,
q1q3, medianq1q3, iqr, range, medianrange, or other R built-in or user-written functions.
* ``cat.stats ``:   summary statistics to include for categorical RHS variables within the levels of the group LHS variable. Options are N, Nmiss, Nmiss2, count, countpct,
countrowpct, countcellpct, or other R built-in or user-written functions.
* ``ordered.stats``: summary statistics to include for categorical RHS variables within the levels of the group LHS variable. Options are N, Nmiss, count, countpct, or other R
built-in or user-written functions.
* ``date.stats``: stats functions to perform for Date variables: Nmiss, median, range, median-
range, q1q3, medianq1q3, or other R built-in or user-written functions.
* stats.labels A named list of labels for all the statistics function names, where the function name is the named element in the list and the value that goes with it is a string
containing the formal name that will be printed in all printed renderings of the output, e.g., list(countpct="Count (Pct)").
* ``digits``: Number of decimal places for numeric values.
* ``digits.count``: Number of decimal places for count values.
* ``digits.p``: Number of decimal places for p-values.
* ``format.p``: Logical, denoting whether to format p-values. See "Details", below.
* ``conf.level``: : Numeric, denoting what confidence level to use for confidence intervals. (See, e.g., binomCI) mcnemar.correct, signed.rank.exact, signed.rank.correct Options for statistical tests. See wilcox.test and mcnemar.test for details.
* ``...``: additional arguments.

#### Details
All tests can be turned off by setting test to FALSE. Otherwise, test are set to default settings in this list, or set explicitly in the formula of tableby.
If format.p is FALSE, digits.p denotes the number of significant digits shown. The p-values will be in exponential notation if necessary. If format.p is TRUE, digits.p will determine the number
of digits after the decimal point to show. If the p-value is less than the resulting number of places, it will be formatted to show so.

#### Value

A list with settings to be used within the paired function.
Author(s)
Ethan Heinzen
See Also
paired, tableby, tableby.control, summary.tableby
