---
title: "``arsenal::summary.compare``"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The summary method for a compare.data.frame object

#### Description

Print a more detailed output of the compare.data.frame object.

#### Usage
<pre><code>

## S3 method for class 'compare.data.frame'
summary(object, ..., show.attrs = FALSE,
max.print.vars = NA, max.print.obs = NA, max.print.diff = 10,
max.print.attrs = NA)
## S3 method for class 'summary.compare.data.frame'
print(x, ..., format = "pandoc")

</code></pre>
#### Arguments

* object An object of class "compare.data.frame", as made by the compare.data.frame S3 method.
* ... Other arguments. In print, these are passed to kable.
* show.attrs: Logical, denoting whether to show the actual attributes which are different. For (e.g.) factors with lots of levels, this can make the tables quite wide, so this
feature is FALSE by default.
* max.print.vars, max.print.obs, max.print.diff, max.print.attrs
Integers denoting the maximum number of differences to report for each of the three tables. Passing NA will print all differences.
* x An object returned by the summary.compare.data.frame function.
* format Passed to kable: the format for the table. The default here is "pandoc". To use the default in kable, pass NULL.

#### Value

An object of class "summary.compare.data.frame" is returned.
See Also
compare.data.frame


