---
title: "A3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(A3)
```

## Boston Housing Prices

#### Description
A dataset containing the prices of houses in the Boston region and a number of features. 

The dataset and the following description is based on that provided by UCI Machine Learning Repository (http://archive.ics.uci.edu/ml/datasets/Housing).

#### Usage 
<pre><code>
data(housing)
</code></pre>

#### Details

* CRIME: Per capita crime rate by town
* ZN: Proportion of residential land zoned for lots over 25,000 sq.ft.
* INDUS: Proportion of non-retail business acres per town
* CHAS: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
* NOX: Nitrogen oxides pollutant concentration (parts per 10 million)
* ROOMS: Average number of rooms per dwelling
* AGE: Proportion of owner-occupied units built prior to 1940
* DISTANCE: Weighted distances to five Boston employment centres
* HIGHWAY: Index of accessibility to radial highways
* TAX: Full-value property-tax rate per ten thousand dollar
* PUPIL.TEACHER: Pupil-teacher ratio by town
* MINORITY: 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
* LSTAT: Percent lower status of the population
* MED.VALUE: Median value of owner-occupied homes in thousands of dollars

#### References
Frank, A.&Asuncion, A. (2010). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml].
Irvine, CA: University of California, School of Information and Computer Science.
Harrison, D. and Rubinfeld, D.L. Hedonic prices and the demand for clean air, J. Environ. Economics & Management, vol.5, 81-102, 1978.
