entropy
Entropy Computation


#### Description 


This function allows you to compute the family of alpha entropy as stated in Martos et al (2018).

#### Usage
<pre><code>
entropy(X,alpha=2,k.neighbor,scale=FALSE)
</code></pre>

#### Arguments 
* X data in a matrix where variables are in columns and observations are in rows.
* alpha a parameter defining the entropy function.
* k.neighbor number of neighbour points to consider in the computation of entropy.
* scale logical variable indicating if scaling is required.

#### Details
The function computes the alpha entropy and the local alpha entropy (see reference for further
details) of a data set using a non parametric density estimator.

#### Value
* local.entropy local entropy relative to each point in the sample.
* entropy estimated entropy.

#### References
Martos, G. et al (2018): Entropy Measures for Stochastic Processes with Applications in Functional
Anomaly Detection. Entropy 20(1): 33 (2018).

#### Examples 
```{r}
require(MASS);
data = mvrnorm(100,c(0,0),diag(2));
entropy(data, alpha = 2, k.neighbor = 10, scale = FALSE)
```
