MTY Muncipal Income Tax Yield
#### Description
Numerical vector of length 11194. details in [Ultsch/Behnisch, 2017; Thrun/Ultsch, 2018].
#### Usage
data("MTY")
References
[Thrun/Ultsch, 2018] Thrun, M. C., & Ultsch, A. : Effects of the payout system of income taxes
to municipalities in Germany, in Papiez, M. & Smiech„ S. (eds.), Proc. 12th Professor Aleksander
Zelias International Conference on Modelling and Forecasting of Socio-Economic Phenomena, pp.
533-542, Cracow: Foundation of the Cracow University of Economics, Cracow, Poland, 2018.
[Ultsch/Behnisch, 2017] Ultsch, A., Behnisch, M.: Effects of the payout system of income taxes to
municipalities in Germany, Applied Geography, Vol. 81, pp. 21-31, 2017.
Examples
data(MTY)
str(MTY)
PDEplot PDE plot
#### Description
This function plots the Pareto probability density estimation (PDE), uses PDEstimationForGauss
and ParetoRadius.
#### Usage
PDEplot(data, paretoRadius = 0, weight = 1, kernels = NULL,
LogPlot = F, PlotIt = TRUE, title =
"ParetoDensityEstimation(PDE)", color = "blue",
xpoints = FALSE, xlim, ylim, xlab = "Data", ylab =
"PDE", ggPlot = ggplot(), sampleSize = 2e+05, lwd = 2)
PDEplot 41
#### Arguments
data numeric vector, data to be plotted.
paretoRadius numeric, the Pareto Radius. If omitted, calculate by paretoRad.
weight numeric, Weight*ParetoDensity is plotted. 1 by default.
kernels numeric vector of kernels. Optional
LogPlot LogLog PDEplot if TRUE, xpoints has to be FALSE. Optional
PlotIt logical, if plot. TRUE by default.
title character vector, title of plot.
color character vector, color of plot.
xpoints logical, if TRUE only points are plotted. FALSE by default.
xlim #### Arguments to be passed to the plot method.
ylim #### Arguments to be passed to the plot method.
xlab #### Arguments to be passed to the plot method.
ylab #### Arguments to be passed to the plot method.
ggPlot ggplot2 object to be plotted upon. Insert an exisiting plot to add a new PDEPlot
to it. Default: empty plot
sampleSize default(200000), sample size, if datavector is to big
lwd linewidth, see plot
Value
kernels numeric vector. The x points of the PDE function.
paretoDensity numeric vector, the PDE(x).
paretoRadius numeric value, the Pareto Radius used for the plot.
ggPlot ggplot2 object. Can be used to further modify the plot or add other plots.
Author(s)
Michael Thrun
References
Ultsch, A.: Pareto Density Estimation: A Density Estimation for Knowledge Discovery, Baier D.,
Wernecke K.D. (Eds), In Innovations in Classification, Data Science, and Information Systems -
Proceedings 27th Annual Conference of the German Classification Society (GfKL) 2003, Berlin,
Heidelberg, Springer, pp, 91-100, 2005.
42 PDEscatter
Examples
x <- rnorm(1000, mean = 0.5, sd = 0.5)
y <- rnorm(750, mean = -0.5, sd = 0.75)
plt <- PDEplot(x, color = "red")$ggPlot
plt <- PDEplot(y, color = "blue", ggPlot = plt)$ggPlot
# Second Example
# ggplotObj=ggplot()
# for(i in 1:length(Variables))
# ggplotObj=PDEplot(Data[,i],ggPlot = ggplotObj)$ggPlot
PDEscatter Scatter Density Plot
#### Description
Pareto density estimation (PDE) [Ultsch, 2005] used for a scatter density plot.
#### Usage
PDEscatter(x, y, na.rm = FALSE, paretoRadius = 0, sampleSize =
round(sqrt(5e+08), -3), NrOfContourLines = 20, Plotter
= "native", DrawTopView = T, xlab = "X", ylab = "Y",
main = "PDEscatter", xlim, ylim, Legendlab_ggplot =
"value")
#### Arguments
x Numeric vector, first feature (for x axis values)
y Numeric vector, second feature (for y axis values)
na.rm Function may not work with non finite values. If these cases should be automatically
removed, set parameter TRUE
paretoRadius Numeric, the Pareto Radius. If omitted (or 0), calculate by paretoRad.
sampleSize Numeric, maximum size of the sample used for calculation. High values increase
runtime significantly.
NrOfContourLines
Numeric, number of contour lines to be drawn. 20 by default.
Plotter String, name of the plotting backend to use. Possible values are: "native", "ggplot",
"plotly"
DrawTopView Boolean, True means contur is drawn, otherwise a 3D plot is drawn. Default:
True
PDEscatter 43
xlab String, title of the x axis. Default: "X", see plot() function
ylab String, title of the y axis. Default: "Y", see plot() function
main string, the same as "main" in plot() function
xlim see plot() function
ylim see plot() function
Legendlab_ggplot
String, in case of Plotter="ggplot" label for the legend. Default: "value"
Details
The PDEscatter function generates the density of the xy data as a z coordinate. Afterwards xyz will
be plotted either as a contour plot or a 3d plot. This function plots the PDE on top of a scatterplot.
Variances of x and y should not differ by extreme numbers, otherwise calculate the percentiles on
both first. The method was succesfully used in [Thrun, 2018; Thrun/Ultsch 2018].
Value
List of:
AnzInPSpheres Number of points within the ParetoRadius of each point
ParetoRadius ParetoRadius used for PDEscatter
Handle Handle of the plot object. Information-string if native R plot is used.
Note
If DrawTopView=FALSE only the plotly option is currently available. If another option is chosen, the
method switches automatically there.
Author(s)
Felix Pape
References
[Thrun, 2018] Thrun, M. C.: Projection Based Clustering through Self-Organization and Swarm
Intelligence, (Ultsch, A. & Huellermeier, E. Eds., 10.1007/978-3-658-20540-9), Doctoral dissertation,
Heidelberg, Springer, ISBN: 978-3658205393, 2018.
[Thrun/Ultsch, 2018] Thrun, M. C., & Ultsch, A. : Effects of the payout system of income taxes
to municipalities in Germany, in Papiez, M. & Smiech„ S. (eds.), Proc. 12th Professor Aleksander
Zelias International Conference on Modelling and Forecasting of Socio-Economic Phenomena, pp.
533-542, Cracow: Foundation of the Cracow University of Economics, Cracow, Poland, 2018.
[Ultsch, 2005] Ultsch, A.: Pareto density estimation: A density estimation for knowledge discovery,
In Baier, D. & Werrnecke, K. D. (Eds.), Innovations in classification, data science, and information
systems, (Vol. 27, pp. 91-100), Berlin, Germany, Springer, 2005.
44 Piechart
Examples
#taken from [Thrun/Ultsch, 2018]
data("ITS")
data("MTY")
Inds=which(ITS<900&MTY<8000)
plot(ITS[Inds],MTY[Inds],main='Bimodality is not visible in normal scatter plot')
PDEscatter(ITS[Inds],MTY[Inds],xlab = 'ITS in EUR',
ylab ='MTY in EUR' ,main='Pareto Density Estimation indicates Bimodality' )
Piechart The pie chart
#### Description
the pie chart represents amount of values given in data.
#### Usage
Piechart(Datavector,Names,Labels,MaxNumberOfSlices,
main='',col,Rline=1,...)
#### Arguments
Datavector [1:n] a vector of n non unique values
Names Optional, [1:k] names to search for in Datavector, if not set unique of Datavector
is calculated.
Labels Optional, [1:k] Labels if they are specially named, if not Names are used.
MaxNumberOfSlices
Default is k, integer value defining how many labels will be shown. Everything
else will be summed up to Other.
main Optional, title below the fan pie, see plot
col Optional, default as other colors in this packages, else the same as in plot
Rline Optional, the radius of the pie in numerical numbers
... Optional, further #### Arguments passed on to plot
Details
If Number of Slices is higher than MaxNumberOfSlices then ABCanalysis is applied (see [Ultsch/Lotsch,
2015]) and group A chosen. If Number of Slices in group A is higher than MaxNumberOfSlices,
then the most important ones out of group A are chosen. If MaxNumberOfSlices is higher than
Slices in group A, additional slices are shown depending on the percentage (from high to low).
Parameters of visualization a set as in [Schwabish, 2014] defined.
Pixelmatrix 45
Value
silent output by calling invisible of a list with
Percentages [1:k] percent values visualized in fanplot
Labels [1:k] see input Labels, only relevant ones
Note
You see in the example below that a pie chart does not visualize such data well contrary to the
fanPlot.
Author(s)
Michael Thrun
References
[Schwabish, 2014] Schwabish, Jonathan A. An Economist’s Guide to Visualizing Data. Journal of
Economic Perspectives, 28 (1): 209-34. DOI: 10.1257/jep.28.1.209, 2014.
[Ultsch/Lotsch, 2015] Ultsch. A ., Lotsch J.: Computed ABC Analysis for Rational Selection
of Most Informative Variables in Multivariate Data, PloS one, Vol. 10(6), pp. e0129767. doi
10.1371/journal.pone.0129767, 2015.
Examples
data(categoricalVariable)
Piechart(categoricalVariable)
Pixelmatrix Plot of a Pixel Matrix
#### Description
Plots Data matrix as a pixel coulour image.
#### Usage
Pixelmatrix(Data, XNames = NULL, LowLim, HiLim,
YNames = NULL, main = '',FillNotFiniteWithHighestValue=FALSE)
46 Plot3D
#### Arguments
Data [1:n,1:d] Data cases in rows (n), variables in columns (d)
LowLim Optional: limits for the color axis
HiLim Optional: limits for the color axis
XNames Optional: Vector - names for the X-ticks
YNames Optional: Vector - names for the Y-ticks
main Optinal: String - Title of the plot
FillNotFiniteWithHighestValue
Optinal, Default FALSE = Non finite values are shown in black, TRUE=non
finite values are transformed to a value higher than the highest value and shown
in this color
Details
Low values are shown in blue and green, middle values in yellow and high values in orange and red.
Author(s)
Michael Thrun, Felix Pape
Examples
data("Lsun3D")
Data=Lsun3D$Data
Pixelmatrix(Data)
Plot3D 3D plot of points
#### Description
A wrapper for Data with systematic clustering colors for either a 2D (x,y) or 3D (x,y,z) plot combined
with a classification
#### Usage
Plot3D(Data,Cls,UniqueColors,size=2,na.rm=FALSE,...)
Plot3D 47
#### Arguments
Data [1:n,1:d] matrix with either d=2 or d=3, if d>3 only the first 3 dimensions are
taken
Cls [1:n] numeric vector of the classification of data with k classes
UniqueColors [1:k] character vector of colors, if not given DataVisualizations::DefaultColorSequence
is used
size size of points
na.rm if na.rm=TRUE, then missing values are removed
... further #### Arguments to be processed by plot3d or geom_point
Details
For geom_point only size and na.rm is available as further #### Arguments.
Note
Uses either geom_point for 2D or plot3d for 3D
Author(s)
Michael Thrun
References
RGL vignette in https://cran.r-project.org/package=rgl
Spin3D in https://www.uni-marburg.de/fb12/arbeitsgruppen/datenbionik/software-en
Examples
#Spin3D similar output
data(Lsun3D)
Plot3D(Lsun3D$Data,Lsun3D$Cls,type='s',radius=0.1,box=FALSE,aspect=TRUE)
rgl::grid3d(c("x", "y", "z"))
#Projected Points with Classification
Data=cbind(runif(500,min=-3,max=3),rnorm(500))
# Classification
Cls=ifelse(Data[,1]>0,1,2)
Plot3D(Data,Cls,UniqueColors = DataVisualizations::DefaultColorSequence[c(1,3)],size=2)
#Points with Non-Overlapping Labels
#require(ggrepel)
Data=cbind(runif(30,min=-1,max=1),rnorm(30,0,0.5))
Names=paste0('VeryLongName',1:30)
ggobj=Plot3D(Data)
ggobj + geom_text_repel(aes(label=Names), size=3)
48 PlotMissingvalues
PlotMissingvalues Plot of the Amount Of Missing Values
#### Description
Percentage of missing values per feature are visualized as a bar plot.
#### Usage
PlotMissingvalues(Data,Names,
WhichDefineMissing=c('NA','DUMMY','.',' '),
PlotIt=TRUE,xlab='Amount Of Missing Values in percent',...)
#### Arguments
Data [1:n,1:d] data cases in rows, variables/features in columns
Names [1:d] optional vector of string describing the names of the features
WhichDefineMissing
[1:d] optional vector of string describing missing values, usefull for character
features.
PlotIt If FALES: Does not plot
xlab x label of bar plot
... Further #### Arguments passed on to barplot, such as main for title
Value
plots not finite and missing values as a bar plot for each feature d and returns with invisible the
amount of missing values as a vector. Works even with character variables, but WhichDefineMissing
cannot be changed at the current version. Please make a suggestion on GitHub how to improve
this.
Note
Does not work with the tibble format, in such a case please call as.data.frame(as.matrix(Data))
Author(s)
Michael Thrun
Examples
data("ITS")
data("MTY")
PlotMissingvalues(cbind(ITS,MTY),Names=c('ITS','MTY'))
PlotProductratio 49
PlotProductratio Product-Ratio Plot
#### Description
The product-ratio plot as defined in [Tukey, 1977, p. 594].
#### Usage
PlotProductratio(x, y, na.rm = FALSE,
main='Product Ratio Analysis',xlab = "Log of Ratio",ylab = "Root of Product", ...)
#### Arguments
x [1:n] positive numerical vector, negativ values are removed automatically
y [1:n] positive numerical vector, negativ values are removed automatically
na.rm Function may not work with non finite values. If these cases should be automatically
removed, set parameter TRUE
main see plot
ylab see plot
xlab see plot
... further #### Arguments passed on to plot
Details
In the case where there are many instances of very small values, but a small number of very large
ones, this plot is usefull [Tukey, 1977, p. 615].
Value
matrix[1:n,2] with sqrt(x*y) and log(x/y) as the two columns
Author(s)
Michael Thrun
References
[Tukey, 1977] Tukey, J. W.: Exploratory data analysis, United States Addison-Wesley Publishing
Company, ISBN: 0-201-07616-0, 1977.
Examples
#Beware: The data does no fit ne requirements for this approach
data('ITS')
data(MTY)
PlotProductratio(ITS,MTY)
50 QQplot






