PmatrixColormap P-Matrix colors
#### Description
Defines the default color sequence for plots made with PDEscatter
#### Usage
data("PmatrixColormap")
Format
Returns the vectors for a (heat) colormap.
QQplot QQplot with a Linear Fit
#### Description
Qantile-quantile plot with a linear fit
#### Usage
QQplot(X,Y,xlab ='X', ylab='Y',col="red",main='',...)
#### Arguments
X [1:n] numerical vector, First Feature
Y 1:n] numerical vector, Second Feature to compare first feature with
xlab x label, see plot ...
ylab y label, see plot
col color of line, see plot
main title of plot, see plot
... other parameters for qqplot
Details
Output is the evaluation of a linear fit of lm called ’line’ and a quantile quantile plot (QQplot).
Sheparddiagram 51
Value
List with
Residuals Output ofresiduals.lm(line)
Summary Output ofsummaryline)
Anova Output ofanova(line)
Author(s)
Michael Thrun
References
Michael, J. R.: The stabilized probability plot, Biometrika, Vol. 70(1), pp. 11-17, 1983.
Sheparddiagram Draws a Shepard Diagram
#### Description
This function plots a Shepard diagram which is a scatter plot of InputDist and OutputDist
#### Usage
Sheparddiagram(InputDists, OutputDists, xlab = "Input Distances",
ylab= "Output Distances", fancy = F,
main = "ProjectionMethod", gPlot = ggplot())
#### Arguments
InputDists [1:n,1:n] with n cases of data in d variables/features: Matrix containing the distances
of the inputspace.
OutputDists [1:n,1:n] with n cases of data in d dimensionalites of the projection method
variables/features: Matrix containing the distances of the outputspace.
xlab Label of the x axis in the resulting Plot.
ylab Label of the y axis in the resulting Plot.
fancy Set FALSE for PC and TRUE for publication
main Title of the Shepard diagram
gPlot ggplot2 object to plot upon.
Value
ggplot2 object containing the plot.
52 ShepardPDEscatter
Author(s)
Michael Thrun
Examples
data("Lsun3D")
Cls=Lsun3D$Cls
Data=Lsun3D$Data
InputDist=as.matrix(dist(Data))
res = stats::cmdscale(d = InputDist, k = 2, eig = TRUE,
add = FALSE, x.ret = FALSE)
ProjectedPoints = as.matrix(res$points)
Sheparddiagram(InputDist,as.matrix(dist(ProjectedPoints)),main = 'MDS')
ShepardPDEscatter Shepard PDE scatter
#### Description
Draws ein Shepard Diagram (scatterplot of distances) with an two-dimensional PDE density estimation
.
#### Usage
ShepardPDEscatter(InputDists, OutputDists, Plotter = "native",
xlab ="Input Distances", ylab = "Output Distances",
main = "ProjectionMethod",sampleSize)
#### Arguments
InputDists [1:n,1:n] with n cases of data in d variables/features: Matrix containing the distances
of the inputspace.
OutputDists [1:n,1:n] with n cases of data in d dimensionalites of the projection method
variables/features: Matrix containing the distances of the outputspace.
xlab Label of the x axis in the resulting Plot.
ylab Label of the y axis in the resulting Plot.
Plotter see PDEscatter for details
main Title of the Shepard diagram
sampleSize Optional, default(50000), reduces a.ount of data for density estimation, if too
many distances given
SignedLog 53
Details
Introduced and described in [Thrun, 2018, p. 63] with examples in [Thrun, 2018, p. 71-72]
Author(s)
Michael Thrun
References
[Thrun, 2018] Thrun, M. C.: Projection Based Clustering through Self-Organization and Swarm
Intelligence, doctoral dissertation 2017, Springer, ISBN: 978-3-658-20540-9, Heidelberg, 2018.
Examples
data("Lsun3D")
Cls=Lsun3D$Cls
Data=Lsun3D$Data
InputDist=as.matrix(dist(Data))
res = stats::cmdscale(d = InputDist, k = 2, eig = TRUE,
add = FALSE, x.ret = FALSE)
ProjectedPoints = as.matrix(res$points)
ShepardPDEscatter(InputDist,as.matrix(dist(ProjectedPoints)),main = 'MDS')
SignedLog Signed Log
#### Description
Computes the Signed Log if Data
#### Usage
SignedLog(Data,Base="Ten")
#### Arguments
Data [1:n,1:d] Data matrix with n cases and d variables
Base Either "Ten", "Two", "Zero", or any number.
Details
A neat transformation for data, it it has a better representation on the log scale.
54 Silhouetteplot
Value
Transformed Data
Note
Number Selections for Base currently experimental.
Author(s)
Michael Thrun
References
Prof. Dr. habil. A. Ultsch, Lectures in Knowledge Discovery, 2014.
See Also
log
Examples
MDplot(SignedLog(cbind(ITS,MTY)*(-1),Base = "Ten"))
Silhouetteplot Silhouette plot of classified data.
#### Description
Silhouette plot of cluster silhouettes for the n-by-d data matrix Data or distance matrix where the
clusters are defined in the vector Cls.
#### Usage
Silhouetteplot(DataOrDistances, Cls, method='euclidean',
PlotIt=TRUE,...)
#### Arguments
DataOrDistances
[1:n,1:d] data cases in rows, variables in columns, if not symmetric
or
[1:n,1:n] distance matrix, if symmetric
Cls numeric vector, [1:n,1] classified data
method Optional if Datamatrix is used, one of "euclidean", "maximum", "manhattan",
"canberra", "binary" or "minkowski". Any unambiguous substring can be given,
see dist
PlotIt Optional, Default:TRUE, FALSE to supress the plot
... If PlotIt=TRUE: Further arguements to barplot
Slopechart 55
Details
"The Silhouette plot is a common unsupervised index for visual evaluation of a clustering [L. R.
Kaufman/Rousseeuw, 2005] [introduced in [Rousseeuw, 1987]]. A reasonable clustering is characterized
by a silhouette width of greater than 0.5, and an average width below 0.2 should be interpreted
as indicating a lack of any substantial cluster structure [Everitt et al., 2001, p. 105]. However,
it is evident that silhouette scores assume clusters that are spherical or Gaussian in shape [Herrmann,
2011, pp. 91-92]" [Thrun, 2018, p. 29].
Value
silh Silhouette values in a N-by-1 vector
Author(s)
Onno Hansen-Goos, Michael Thrun
References
[Thrun, 2018] Thrun, M. C.: Projection Based Clustering through Self-Organization and Swarm
Intelligence, doctoral dissertation 2017, Springer, ISBN: 978-3-658-20539-3, Heidelberg, 2018.
[Rousseeuw, 1987] Rousseeuw, Peter J.: Silhouettes: a Graphical Aid to the Interpretation and
Validation of Cluster Analysis, Computational and Applied Mathematics, 20, p.53-65, 1987.
Examples
data("Lsun3D")
Cls=Lsun3D$Cls
Data=Lsun3D$Data
#clear cluster structure
plot(Data[,1:2],col=Cls)
#However, the silhouette plot does not indicate a very good clustering in cluster 1 and 2
Silhouetteplot(Data,Cls = Cls,main='Silhouetteplot')
Slopechart Slope Chart
#### Description
ABC analysis improved slope chart
56 Slopechart
#### Usage
Slopechart(FirstDatavector,
SecondDatavector,
Names,
Labels,
MaxNumberOfSlices,
TopLabels=c('FirstDatavector','SecondDatavector'),
main='Comparision of Descending Frequency')
#### Arguments
FirstDatavector
[1:n] a vector of n non unique values - a features
SecondDatavector
[1:m] a vector of n non unique values - a second feature
Labels Optional, [1:k] Labels if they are specially named, if not Names are used.
Names [1:k] names to search for in Datavector, if not set unique of Datavector is calculated.
MaxNumberOfSlices
Default is k, integer value defining how many labels will be shown. Everything
else will be summed up to Other.
TopLabels Labels of of feature names
main title of the plot
Details
still experimental.
Value
silent output by calling invisible of a list with
Percentages [1:k] percent values visualized in fanplot
Labels [1:k] see input Labels, only relevant ones
Author(s)
Michael Thrun
References
[Gohil, 2015] Gohil, Atmajitsinh. R data Visualization cookbook. Packt Publishing Ltd, 2015.
StatPDEdensity 57
See Also
Piechart, Fanplot
Examples
## will follow
StatPDEdensity Pareto Density Estimation
#### Description
Density Estimation for ggplot with a clear model behind it.
Format
The format is: Classes ’StatPDEdensity’, ’Stat’, ’ggproto’ <ggproto object: Class StatPDEdensity,
Stat> aesthetics: function compute_group: function compute_layer: function compute_panel: function
default_aes: uneval extra_params: na.rm finish_layer: function non_missing_aes: parameters:
function required_aes: x y retransform: TRUE setup_data: function setup_params: function super:
<ggproto object: Class Stat>
Details
PDE was published in [Ultsch, 2005], short explanation in [Thrun, Ultsch 2018] and the PDE
optimized violin plot was published in [Thrun et al., 2018].
References
[Ultsch,2005] Ultsch, A.: Pareto density estimation: A density estimation for knowledge discovery,
in Baier, D.; Werrnecke, K. D., (Eds), Innovations in classification, data science, and information
systems, Proc Gfkl 2003, pp 91-100, Springer, Berlin, 2005.
[Thrun, Ultsch 2018] Thrun, M. C., & Ultsch, A. : Effects of the payout system of income taxes
to municipalities in Germany, in Papiez, M. & Smiech„ S. (eds.), Proc. 12th Professor Aleksander
Zelias International Conference on Modelling and Forecasting of Socio-Economic Phenomena, pp.
533-542, Cracow: Foundation of the Cracow University of Economics, Cracow, Poland, 2018.
[Thrun et al, 2018] Thrun, M. C., Pape, F., & Ultsch, A. : Benchmarking Cluster Analysis Methods
using PDE-Optimized Violin Plots, Proc. European Conference on Data Analysis (ECDA),
accepted, Paderborn, Germany, 2018.
58 stat_pde_density
stat_pde_density Calculate Pareto density estimation for ggplot2 plots
#### Description
This function enables to replace the default density estimation for ggplot2 plots with the Pareto
density estimation [Ultsch, 2005]. It is used for the PDE-Optimized violin plot published in [Thrun
et al, 2018].
#### Usage
stat_pde_density(mapping = NULL,
data = NULL,
geom = "violin",
position = "dodge",
...,
trim = TRUE,
scale = "area",
na.rm = FALSE,
show.legend = NA,
inherit.aes = TRUE)
#### Arguments
mapping Set of aesthetic mappings created by aes() or aes_(). If specified and inherit.aes = TRUE
(the default), it is combined with the default mapping at the top level of the plot.
You must supply mapping if there is no plot mapping.
data The data to be displayed in this layer. There are three options:
If NULL, the default, the data is inherited from the plot data as specified in the
call to ggplot().
A data.frame, or other object, will override the plot data. All objects will be
fortified to produce a data frame. See fortify() for which variables will be
created.
A function will be called with a single argument, the plot data. The return
value must be a data.frame., and will be used as the layer data.
geom The geometric object to use display the data
position Position adjustment, either as a string, or the result of a call to a position adjustment
function.
... Other #### Arguments passed on to layer(). These are often aesthetics, used to set
an aesthetic to a fixed value, like color = "red" or size = 3. They may also
be parameters to the paired geom/stat.
trim This parameter only matters if you are displaying multiple densities in one plot.
If ‘FALSE‘, the default, each density is computed on the full range of the data.
If ‘TRUE‘, each density is computed over the range of that group: this typically
means the estimated x values will not line-up, and hence you won’t be able to
stack density values.
stat_pde_density 59
scale When used with geom_violin: if "area" (default), all violins have the same area
(before trimming the tails). If "count", areas are scaled proportionally to the
number of observations. If "width", all violins have the same maximum width.
na.rm If FALSE (the default), removes missing values with a warning. If TRUE silently
removes missing values.
show.legend logical. Should this layer be included in the legends? NA, the default, includes if
any aesthetics are mapped. FALSE never includes, and TRUE always includes. It
can also be a named logical vector to finely select the aesthetics to display.
inherit.aes If FALSE, overrides the default aesthetics, rather than combining with them.
This is most useful for helper functions that define both data and aesthetics and
shouldn’t inherit behaviour from the default plot specification, e.g. borders().
Details
Pareto Density Estimation (PDE) is a method for the estimation of probability density functions
using hyperspheres. The Pareto-radius of the hyperspheres is derived from the optimization of
information for minimal set size. It is shown, that Pareto Density is the best estimate for clusters of
Gaussian structure. The method is shown to be robust when cluster overlap and when the variances
differ across clusters.
Author(s)
Felix Pape
References
Ultsch, A.: Pareto density estimation: A density estimation for knowledge discovery, in Baier, D.;
Werrnecke, K. D., (Eds), Innovations in classification, data science, and information systems, Proc
Gfkl 2003, pp 91-100, Springer, Berlin, 2005.
[Thrun et al, 2018] Thrun, M. C., Pape, F., & Ultsch, A. : Benchmarking Cluster Analysis Methods
using PDE-Optimized Violin Plots, Proc. European Conference on Data Analysis (ECDA),
accepted, Paderborn, Germany, 2018.
See Also
[ggplot2]stat_density
Examples
miris <- reshape2::melt(iris)
ggplot2::ggplot(miris,
mapping = ggplot2::aes_string(y = 'value', x = 'variable')) +
ggplot2::geom_violin(stat = "PDEdensity")
60 Worldmap
