
DefaultColorSequence Default color sequence for plots
#### Description
Defines the default color sequence for plots made within the Projections package.
#### Usage
data("DefaultColorSequence")
Format
A vector with 562 different strings describing colors for plots.
DualaxisClassplot Dualaxis Classplot
#### Description
Allows to plot two time series or features with one or two classification(a) as labeled scatter plots.
The colors are the labels defined by the classification. Usefull to see if temporal clustering has time
dependent variations and for Hidden Markov Models (see Mthrun/RHmm on GitHub).
#### Usage
DualaxisClassplot(X, Y1, Y2, Cls1,
Cls2, xlab = "X", y1lab = "Y1", y2lab = "Y2",
main = "Dual Axis Class Plot", Colors, Showgrid = TRUE, SaveIt = FALSE)
#### Arguments
X [1:n] numeric vector or time
Y1 [1:n] numeric vector of feauture
Y2 [1:n] numeric vector of feauture
Cls1 [1:n] numeric vector defining a classification of k1 classes
Cls2 Optional, [1:n] numeric vector defining a classification of k2 classes for Y2
xlab Optional, string
y1lab Optional, string
y2lab Optional, string
main Optional, string
Colors [1:(k1+k2)] Colornames
Showgrid Optional, boolean
SaveIt Optional, boolean
DualaxisLinechart 21
Value
plotly object
Author(s)
Michael Thrun
See Also
Classplot
Examples
##ToDo
