---
title: "``DataVisualizations::Sheparddiagram``"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DataVisualizations)
```
Sheparddiagram Draws a Shepard Diagram
#### Description
This function plots a Shepard diagram which is a scatter plot of InputDist and OutputDist

#### Usage
<pre><code>
Sheparddiagram(InputDists, OutputDists, xlab = "Input Distances",
ylab= "Output Distances", fancy = F,
main = "ProjectionMethod", gPlot = ggplot())
</code></pre>

#### Arguments
InputDists [1:n,1:n] with n cases of data in d variables/features: Matrix containing the distances
of the inputspace.
OutputDists [1:n,1:n] with n cases of data in d dimensionalites of the projection method
variables/features: Matrix containing the distances of the outputspace.
xlab Label of the x axis in the resulting Plot.
ylab Label of the y axis in the resulting Plot.
fancy Set FALSE for PC and TRUE for publication
main Title of the Shepard diagram
gPlot ggplot2 object to plot upon.

#### Value
ggplot2 object containing the plot.

#### Author(s)
Michael Thrun

#### Examples
data("Lsun3D")
Cls=Lsun3D$Cls
Data=Lsun3D$Data
InputDist=as.matrix(dist(Data))
res = stats::cmdscale(d = InputDist, k = 2, eig = TRUE,
add = FALSE, x.ret = FALSE)
ProjectedPoints = as.matrix(res$points)
Sheparddiagram(InputDist,as.matrix(dist(ProjectedPoints)),main = 'MDS')
